<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icono.ico</ApplicationIcon>

    
    <AssemblyName>SistemaGestion</AssemblyName>
    <Product>Sistema de Gestión</Product>
    <AssemblyTitle>Sistema de Gestión</AssemblyTitle>


    <Version>1.0.9</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="icono.ico"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="PdfSharp" Version="6.2.4" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

</Project>
